version: "3"

services: 
  players:
    build: ./players
    ports:
      - 5002:80
    volumes:
      - ./players:/home/app

  site:
    build: ./site
    ports: 
      - 5000:80
    depends_on:
      - players
    volumes:
      - ./site:/src
  
  # The volume part is to make sure that if changes are made on the code file, its implemented on the output.
