version: "3"

networks:
  core:
    driver: bridge
  site:
    driver: bridge
    
services: 
  db:
    build: ./db
    networks:
      - core
  bomasi:
    build: ./bomasi
    networks:
      - core
    volumes:
      - ./bomasi:/app
    ports:
      - 5001:80
    depends_on:
      - db
  prices:
    build: ./prices
    networks:
         - core
         - site
    volumes:
      - ./prices:/app
    ports:
      - 5002:80
    depends_on:
      - bomasi  
  site:
    build: ./site
    networks:
        - core
    volumes:
      - ./site:/src
    ports:
      - 5000:80
    depends_on:
      - prices

  # The introduction of the network part is to bring to help to prevent some part of output from displaying at the frontend side of the
  # website
   